# Generated by Django 4.1 on 2022-08-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='town_id',
            new_name='town',
        ),
    ]
