# Generated by Django 4.1 on 2022-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_rename_lan_towns_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towns',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
