# Generated by Django 4.1 on 2022-08-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_towns_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='weather',
            new_name='temp',
        ),
    ]
